export const USERS = [
    {
        id: "u1",
        name: "Carlos",
        surname: "Méndez",
        username: "carlos.m",
        password: "password123",
    },
    {
        id: "u2",
        name: "Ana",
        surname: "García",
        username: "ana.garcia",
        password: "securepass",
    },
    {
        id: "u3",
        name: "Luis",
        surname: "Pérez",
        username: "luis.perez",
        password: "mypassword",
    },
    {
        id: "u4",
        name: "María",
        surname: "Hernández",
        username: "maria.hernandez",
        password: "maria2023",
    },
    {
        id: "u5",
        name: "Jorge",
        surname: "Torres",
        username: "jorge.torres",
        password: "jorgepass",
    },
    {
        id: "u6",
        name: "Sofía",
        surname: "Romero",
        username: "sofia.romero",
        password: "sofialover",
    },
    {
        id: "u7",
        name: "Andrés",
        surname: "Suárez",
        username: "andres.suarez",
        password: "andres123",
    },
    {
        id: "u8",
        name: "Gabriela",
        surname: "Salazar",
        username: "gabriela.salazar",
        password: "gabriela2023",
    },
    {
        id: "u9",
        name: "Daniel",
        surname: "Ceballos",
        username: "daniel.ceballos",
        password: "daniel123",
    },
    {
        id: "u10",
        name: "Valentina",
        surname: "Lopez",
        username: "valentina.lopez",
        password: "valentina123",
    },
];
