export const DEVICES = [
  {
    charge: 45,
    temperature: 59,
    name: "Torre Moñitos",
    id: "AK1234",
    criticLevel: 40,
  },
  {
    charge: 85,
    temperature: 65,
    name: "Torre La Candelaria",
    id: "AK1235",
    criticLevel: 45,
  },
  {
    charge: 70,
    temperature: 55,
    name: "Torre El Poblado",
    id: "AK1236",
    criticLevel: 40,
  },
  {
    charge: 90,
    temperature: 72,
    name: "Torre Chapinero",
    id: "AK1237",
    criticLevel: 40,
  },
  {
    charge: 60,
    temperature: 58,
    name: "Torre Santa Marta",
    id: "AK1238",
    criticLevel: 40,
  },
  {
    charge: 75,
    temperature: 62,
    name: "Torre Barranquilla",
    id: "AK1239",
    criticLevel: 40,
  },
  {
    charge: 80,
    temperature: 70,
    name: "Torre Bucaramanga",
    id: "AK1240",
    criticLevel: 40,
  },
  {
    charge: 92,
    temperature: 77,
    name: "Torre Pereira",
    id: "AK1241",
    criticLevel: 40,
  },
  {
    charge: 50,
    temperature: 53,
    name: "Torre Cartago",
    id: "AK1242",
    criticLevel: 40,
  },
  {
    charge: 67,
    temperature: 64,
    name: "Torre Sincelejo",
    id: "AK1243",
    criticLevel: 40,
  },
  {
    charge: 100,
    temperature: 68,
    name: "Torre Villavicencio",
    id: "AK1244",
    criticLevel: 40,
  },
];
